// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzpzzxpymbfkuwqysjex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6cHp6eHB5bWJma3V3cXlzamV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTkyNjUsImV4cCI6MjA3MDA5NTI2NX0.zPU0UOkD0j4DBQMJ2gwHW2y2FYkd9odz7Dewvcr0ScU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});